[package]
name = "crypto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.11.8"
tonic = "0.8"
chacha20poly1305 = "0.10.1"

[build-dependencies]
tonic-build = "0.8"